### ISSUE TITLE
Get the total power consumption so far after a new VM is placed?

### ISSUE THREAD

**Issue by marwaThabet** [manoelcampos/cloudsimplus#316]
To report an issue or feature request, you have to provide the information below.

# WHEN REPORTING AN ISSUE:

## Actual behavior 
Why when I do call  datacenter.getPower after each VM allocation, the output is always 0?
## Expected behavior
For example my strategy consumes 251.2 Kw at the end of the simulation, the results during the simulation should be incremental until it reaches the value 251.2 Kw.
## If the issue is related to a specific method, provide a test case that fails in order to show the problem
In the DataCenter class:
	protected void processVmCreate(SimEvent ev, boolean ack) {
		Vm vm = (Vm) ev.getData();

		boolean result = getVmAllocationPolicy().allocateHostForVm(vm);
        
		if (ack) {
			int[] data = new int[3];
			data[0] = getId();
			data[1] = vm.getId();

			if (result) {
				data[2] = CloudSimTags.TRUE;
			} else {
				data[2] = CloudSimTags.FALSE;
			}
			send(vm.getUserId(), CloudSim.getMinTimeBetweenEvents(), CloudSimTags.VM_CREATE_ACK, data);
		}

		if (result) {
			getVmList().add(vm);

			if (vm.isBeingInstantiated()) {
				vm.setBeingInstantiated(false);
			}

			vm.updateVmProcessing(CloudSim.clock(), getVmAllocationPolicy().getHost(vm).getVmScheduler()
					.getAllocatedMipsForVm(vm));
		}
         
		if (result) {
				double energy=(double)((PowerDatacenter)this).getPower() / (3600 * 1000); 
                                System.out.println(energy); //always prints 0
		
			 
		}

	}

## If it is a wider problem or you don't know where it happens, please provide a minimal simulation example which reproduces the problem

 In helper and in the function print results, we have:
double energy = datacenter.getPower() / (3600 * 1000);
the value of power is set by setPower in the function:
updateCloudetProcessingWithoutSchedulingFutureEventsForce()
I tried to use the same code to have the energy consumption progress after each assignment but it's always 0.
I want to use the same formula that gives the final value after the total simulation by default!
But I cannot find it !
## Specifications like the version of the project, operating system or workload file used

------------------------------------------------------------------------------------------------------------------------------------

# WHEN REQUESTING A FEATURE:

**Comment by manoelcampos** [comment]
This code isn't from **CloudSim Plus**, but from **CloudSim**. If you want help, upgrade to CloudSim Plus.

**Comment by manoelcampos** [comment]
CloudSim has lots of critical bugs, some of them related to power module. Check [features 2 and 5 here](https://cloudsimplus.org/#exclusive-features) and all [power-related fixed issues here](https://github.com/manoelcampos/cloudsimplus/issues?q=is%3Aissue+is%3Aclosed+label%3Apower).
