### ISSUE TITLE
Questions for Horizontal VM Scaling (Auto Up/Down Scaling) 

### ISSUE THREAD

**Issue by syu180** [manoelcampos/cloudsimplus#337]
Hi, i have 3 questions ,

1.for Horizontal VM Scaling (Auto Up/Down Scaling), do u think it is good to use this to simualte pods auto scaling like in K8S?
2. when i run this sample, that log showed when vm cpu overload, then will reqest 4 vms to be created, but after created, i found the new vms did not get any cloudets, and then get deduction of it, strange that meantime there are another 4 vms created, see log files below.
3. which Google Group that i can subscribe to for further questions. is this:https://groups.google.com/group/cloudsim-plus?
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Sending Cloudlet 10 to Vm 2 in Host 2/DC 1.
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Sending Cloudlet 11 to Vm 3 in Host 3/DC 1.
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Sending Cloudlet 12 to Vm 4 in Host 4/DC 1.
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Sending Cloudlet 13 to Vm 5 in Host 5/DC 1.
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: All 4 waiting Cloudlets submitted to some VM.
�[0;39m Time 10.32: Vm 0 CPU Usage: 100.00% ( 2 vCPUs. Running Cloudlets: #2) Upper Threshold: 0.70 Is Overload: true
Time 10.32: Vm 1 CPU Usage: 100.00% ( 2 vCPUs. Running Cloudlets: #3) Upper Threshold: 0.70 Is Overload: true
Time 10.32: Vm 2 CPU Usage: 100.00% ( 2 vCPUs. Running Cloudlets: #2) Upper Threshold: 0.70 Is Overload: true
Time 10.32: Vm 3 CPU Usage: 0.00% ( 2 vCPUs. Running Cloudlets: #0) Upper Threshold: 0.70 Is Overload: false
Time 10.32: Vm 4 CPU Usage: 0.00% ( 2 vCPUs. Running Cloudlets: #0) Upper Threshold: 0.70 Is Overload: false
Time 10.32: Vm 5 CPU Usage: 0.00% ( 2 vCPUs. Running Cloudlets: #0) Upper Threshold: 0.70 Is Overload: false
Time 10.32: Vm 6 CPU Usage: 0.00% ( 2 vCPUs. Running Cloudlets: #0) Upper Threshold: 0.70 Is Overload: false
Time 10.32: Vm 7 CPU Usage: 0.00% ( 2 vCPUs. Running Cloudlets: #0) Upper Threshold: 0.70 Is Overload: false
�[31mWARN 15.32: CloudletSchedulerTimeShared: Cloudlet 8 requested 512 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
�[0;39m�[31mWARN 15.32: CloudletSchedulerTimeShared: Cloudlet 8 requested 1000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
�[0;39m�[34mINFO 15.32: HorizontalVmScalingSimpleVm 0: Requesting creation of Vm 8 to receive new Cloudlets in order to balance load of Vm 0. 0 CPU usage is 100.0%
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: List of 1 VMs submitted to the broker during simulation execution. VMs creation request sent to Datacenter.
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Trying to create Vm 8 in DatacenterSimple1
�[0;39m�[31mWARN 15.32: CloudletSchedulerTimeShared: Cloudlet 5 requested 512 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
�[0;39m�[31mWARN 15.32: CloudletSchedulerTimeShared: Cloudlet 5 requested 1000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
�[0;39m�[31mWARN 15.32: CloudletSchedulerTimeShared: Cloudlet 9 requested 512 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
�[0;39m�[31mWARN 15.32: CloudletSchedulerTimeShared: Cloudlet 9 requested 1000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
�[0;39m�[34mINFO 15.32: HorizontalVmScalingSimpleVm 1: Requesting creation of Vm 9 to receive new Cloudlets in order to balance load of Vm 1. 1 CPU usage is 100.0%
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: List of 1 VMs submitted to the broker during simulation execution. VMs creation request sent to Datacenter.
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Trying to create Vm 9 in DatacenterSimple1
�[0;39m�[31mWARN 15.32: CloudletSchedulerTimeShared: Cloudlet 6 requested 512 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
�[0;39m�[31mWARN 15.32: CloudletSchedulerTimeShared: Cloudlet 6 requested 1000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
�[0;39m�[34mINFO 15.32: HorizontalVmScalingSimpleVm 2: Requesting creation of Vm 10 to receive new Cloudlets in order to balance load of Vm 2. 2 CPU usage is 100.0%
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: List of 1 VMs submitted to the broker during simulation execution. VMs creation request sent to Datacenter.
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Trying to create Vm 10 in DatacenterSimple1
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Requesting Vm 4 destruction.
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Requesting Vm 5 destruction.
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Requesting Vm 6 destruction.
�[0;39m�[34mINFO 15.32: DatacenterBrokerSimple2: Requesting Vm 7 destruction.
�[0;39m�[34mINFO 15.32: VmAllocationPolicySimple: Vm 8 has been allocated to Host 8/DC 1
�[0;39m�[34mINFO 15.32: VmAllocationPolicySimple: Vm 9 has been allocated to Host 9/DC 1
�[0;39m�[34mINFO 15.32: VmAllocationPolicySimple: Vm 10 has been allocated to Host 10/DC 1
�[0;39m�[31mWARN 15.32: DatacenterSimple: Vm 4 destroyed on Host 4/DC 1. It had a total of 1 cloudlets (running + waiting). Some events may have been missed. You can try: (a) decreasing CloudSim's minTimeBetweenEvents and/or Datacenter's schedulingInterval attribute; (b) increasing broker's Vm destruction delay for idle VMs if you set it to zero; (c) defining Cloudlets with smaller length (your Datacenter's scheduling interval may be smaller than the time to finish some Cloudlets).
�[0;39m�[31mWARN 15.32: DatacenterSimple: Vm 5 destroyed on Host 5/DC 1. It had a total of 1 cloudlets (running + waiting). Some events may have been missed. You can try: (a) decreasing CloudSim's minTimeBetweenEvents and/or Datacenter's schedulingInterval attribute; (b) increasing broker's Vm destruction delay for idle VMs if you set it to zero; (c) defining Cloudlets with smaller length (your Datacenter's scheduling interval may be smaller than the time to finish some Cloudlets).
�[0;39m�[34mINFO 15.32: DatacenterSimple: Vm 6 destroyed on Host 6/DC 1.
�[0;39m�[34mINFO 15.32: DatacenterSimple: Vm 7 destroyed on Host 7/DC 1.

**Comment by manoelcampos** [comment]
In order to get help, check [this link](https://github.com/manoelcampos/cloudsimplus#docs-help).
