### ISSUE TITLE
A command line given in README.md doesn't work

### ISSUE THREAD

**Issue by JoaoLRezende** [manoelcampos/cloudsimplus#347]
## Problem 
Executing ```sh script/bootstrap.sh```, as suggested in README.md, doesn't work on GNU.

## Elaboration

Section 4.2 of [README.md](https://github.com/manoelcampos/cloudsimplus/blob/master/README.md#42-downloading-sources-via-command-line) suggests that commands of the following form be used to run examples:
```sh script/bootstrap.sh package.ExampleClassName```

However, on GNU, trying to execute `sh script/bootstrap.sh` yields the following error message:
`script/bootstrap.sh: 18: Syntax error: "(" unexpected`

This seems to be because, when invoked as `sh`, Bash executes in [POSIX mode](https://www.gnu.org/software/bash/manual/bash.html#Bash-POSIX-Mode). In that mode, Bash doesn't support the function-definition syntax that is used on [line 18](https://github.com/manoelcampos/cloudsimplus/blob/2ca051a2cdcd95c2e93224b9654ff7ee3bf4e770/script/bootstrap.sh#L18) of script/bootstrap.sh. There's some discussion on this [here](https://unix.stackexchange.com/questions/73750/difference-between-function-foo-and-foo).

This can be fixed by invoking Bash as `bash` instead:
```bash script/bootstrap.sh```

I observed this on Ubuntu 20.04.

**Comment by manoelcampos** [comment]
That is new for me 😮 . I followed the discussion and there is even a semantic difference when using the function keyword. Thanks for reporting.
