### ISSUE TITLE
Availability always returns 100% in the HostFaultInjectionExample1.java

### ISSUE THREAD

**Issue by Abhishek262** [manoelcampos/cloudsimplus#356]
# Issue
## Actual behavior 
Avialability gives 100% in all cases, since MTTR value is always 0. Is this value calculated or do we have to set it on our own?
Hard Setting this value to something changes the availability, as expected. This means MTTR isn't being updated properly?
We've tried it for various configurations as well.

## Expected behavior

The availablity result is updated accordingly.

## If it is a wider problem or you don't know where it happens, please provide a minimal simulation example which reproduces the problem
Running HostInjectionExample1.java first gave us a NullException, then we passed broker as an argument to fault.getTotalFaultsNumber(broker),fault.meanTimeToRepairVmFaultsInMinutes(broker),fault.meanTimeBetweenVmFaultsInMinutes(broker),fault.availability(broker) and availability always seems to be 100%.

Are we doing something wrong here? If so, help would be appreciated

## Specifications like the version of the project, operating system or workload file used
We've cloned the latest version and are using ubuntu  20.04.

**Comment by manoelcampos** [comment]
Hello @Abhishek262 

Thanks for reporting the issue.
This fault injection feature is old and I just reviewed its implementation.
Check PR #357 for progress.
The NPE issue was already fixed there.
