### ISSUE TITLE
VM submission delay working incorrectly

### ISSUE THREAD

**Issue by fabianishere** [manoelcampos/cloudsimplus#366]
Hi, I am running into issues when setting a submission delay for virtual machines, where bound cloudlets are not scheduled on the delayed VMs until all delayed VMs have started.

## Actual behavior 
Bound cloudlets are only started on delayed VMs after all delayed VMs have started. 

## Expected behavior
Bound cloudlets should start as soon as the delayed VM it is bound to, is started.

## Examples

- [DynamicVmsArrival2.java](https://github.com/manoelcampos/cloudsimplus/blob/master/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/dynamic/DynamicVmsArrival2.java) reproduces the issue
- [InterDatacenterMigration1](https://github.com/manoelcampos/cloudsimplus/blob/master/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/migration/InterDatacenterMigration1.java) shows that changes may avoid the broker to try a different datacenter when current one doesn't have enough resources for VMs.

## Environment
- CloudSim Plus 7.1.1
- macOS Big Sur
- Oracle JDK 17.0.1

## Possible Solution
I suspect the issue is related to the following commit (and in particular the highlighted code): https://github.com/manoelcampos/cloudsimplus/commit/1979280071d47d860d0c42ac6ae11bb468d412f1#diff-98f6dcd8de723679760e7f8a870e1081ecdc3002bf0ce87d7d77f2d6f8c13af0R386

Is the following condition actually necessary there: `delayed < vmWaitingList.size()`

**Comment by manoelcampos** [comment]
Hello @fabianishere, thanks for reporting.
You correctly pointed out the source of the issue.
This has been done this way since CloudSim and I haven't bothered to change it.
But you showed it's an actual issue.

I have copied your gist to a new DynamicVmsArrival2.java, giving you the credits.

Check PR #367 for details (WIP).

**Comment by fabianishere** [comment]
Thank you @manoelcampos for the swift response!

I have tested the fix proposed in #367 (https://github.com/manoelcampos/cloudsimplus/pull/367/commits/39b68172574c1c734e94d70ee22ef18dc6a12586) and it seems to resolve the issue.

**Comment by manoelcampos** [comment]
Yeah, but it breaks inter-datacenter migration as I expected.
Working on it.

**Comment by manoelcampos** [comment]
Hey @fabianishere,

Thanks for reporting and pointing the direction. It speeded the process up. 
The changes have just been merged.

If you haven't given CloudSim Plus a star, take a second to do it and help the project.
Very appreciated all your contribution.

**Comment by manoelcampos** [comment]
Hey @fabianishere 
After fixing this issue, there was a regression on #331.
I've just fixed it on 9cd0da1.
The examples here and at #331 are working as expected.
