### ISSUE TITLE
Wrong ExecTime

### ISSUE THREAD

**Issue by Vtrust** [manoelcampos/cloudsimplus#368]
# WHEN REPORTING AN ISSUE:
windows11 21H2
JDK 17.0.1
![image](https://user-images.githubusercontent.com/16085476/141266427-63b7f909-e37f-4bd1-91ee-8384ba53046f.png)

run `src/main/java/org/cloudsimplus/examples/schedulers/CloudletSchedulerSpaceSharedExample1.java`

## Actual behavior 
![image](https://user-images.githubusercontent.com/16085476/141265094-1d6dd960-6822-4667-8282-1ca2b7abf49f.png)
The output 'ExecTime' is not right. :dizzy_face:

## Expected behavior
The execution time of all cloudlets  should be same.

**Comment by manoelcampos** [comment]
Hello @Vtrust 
Thanks for reporting. This is just a configuration issue.
Check the changes and message on commit 032286f8f10251899ad33b85b259eb9ba063aee7 for details.

If you haven't given CloudSim Plus a star, please take a second to to that and help the project.
Appreciated.

**Comment by Vtrust** [comment]
> Hello @Vtrust Thanks for reporting. This is just a configuration issue. Check the changes and message on commit [032286f](https://github.com/manoelcampos/cloudsimplus/commit/032286f8f10251899ad33b85b259eb9ba063aee7) for details.
> 
> If you haven't given CloudSim Plus a star, please take a second to do that and help the project. Appreciated.

It works， thank you very much!
