### ISSUE TITLE
Set a Cloudlet to execute for a certain amount of TIME instead of MI

### ISSUE THREAD

**Issue by sun-lingyu** [manoelcampos/cloudsimplus#373]
# REQUESTING A FEATURE:

## Detailed information about how the feature should work
When creating a cloudlet, set it to execute for a certain amount of TIME instead of MI(Million Instructions).

## An example scenario where this feature should be used
In PlanetLab example, we may want the cloudlet to finish as soon as the PlanetLab trace file finishes. But currently, the trace is replayed in a circular way until the cloudlet finishes all its MI.

## A brief explanation of why you think this feature is useful
It will be useful for people doing utilization-oriented VM scheduling simulation based on PlanetLab traces.

**Comment by manoelcampos** [comment]
Hey @sun-lingyu 
That is an interesting feature, but I need to understand it to check how it should work.

PlanetLab files have (by default) 288 lines, each one representing a CPU utilization for a time interval or 5 minutes (300 seconds), totaling 86400 seconds. Consider you have a cloudlet with X PEs running into a VM with at least x PEs. You can use: 

- a CloudletSchedulerSpaceShared to ensure that such a cloudlet is not preempted;
- or a CloudletSchedulerTimeShared inside a VM where the number of virtual PEs is equal or higher to the total number of PEs required by all cloudlets running into that VM.

**In any of those scenarios, we could compute the cloudlet length to ensure it will execute for a given time period if it relies on a UtilizationModelFull (using 100% of CPU all the time)**. In this case, if your VM PEs have 1000 MIPS (MI/s) capacity, to make your cloudlet run for the 86400 seconds (the length of the trace file), the cloudlet length must be `1000 * 86400 = 86400000 MI`.

However, using a trace file, the cloudlet won't use 100% of the CPU all the time, therefore we can't compute cloudlet's length. 

If you just want something simpler such as a Cloudlet `stopTime` attribute, that will be easier to implement and may be useful for other researchers too.

**Comment by sun-lingyu** [comment]
> However, using a trace file, the cloudlet won't use 100% of the CPU all the time, therefore we can't compute cloudlet's length.

This is exactly the problem I encountered with. So what I'd like to have is a `lifetime` attribute for a cloudlet to make sure that it runs for a certain time period when using a utilization trace file.

**Comment by sun-lingyu** [comment]
Hello, @manoelcampos 
So if you think this feature is worth adding, am I responsible for implementing it? Or would you implement it by yourself? (Sorry for this stupid question, since this is my first github issue.)

**Comment by manoelcampos** [comment]
I think it's interesting. Do you think you're able to implement that? I'll give you all the support you need.
