### ISSUE TITLE
VerticalVmScalingSimple tries to set the capacity of VM to zero when performing down scaling

### ISSUE THREAD

**Issue by IbrahemMouhamad** [manoelcampos/cloudsimplus#378]
# ISSUE:
The `ResourceManageableAbstract.removeCapacity()` method reduces the capacity of a resource, but it does not check the value of the subtraction `getCapacity()-capacityToRemove` which may be zero when calling `setCapacity` function. This will cause an Exception like `The Processor's number of PEs must be greater than 0`.
This exception can be avoided early in `VmAllocationPolicyAbstract.scaleVmPesUpOrDown()` method by adding an if statement to check if `scaling.isVmUnderloaded()` is true and VM capacity is equal to `pesNumberForScaling` value, then it should return `false` and does not perform a down VM Pes scaling.
## Actual behavior
`VerticalVmScalingSimple` tries to set the capacity of VM when performing a down scaling, which throw an exception.

## Expected behavior
`VerticalVmScalingSimple` should check the new value of the capacity before trying to set it.

## If the issue is related to a specific method, provide a test case that fails in order to show the problem
To reproduce the issue, try to run the example `VerticalVmCpuScalingExample`  after changing `VM_PES `value to 1 and commenting the line below to use a default `ResourceScalingGradual`.

https://github.com/manoelcampos/cloudsimplus/blob/2184bb48d8870d2bd519122a78b09683bd18bad2/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/autoscaling/VerticalVmCpuScalingExample.java#L267

## Specifications like the version of the project, operating system or workload file used
CloudSimPlus `v7.2.0`

**Comment by manoelcampos** [comment]
Hello @IbrahemMouhamad 
Sorry for the late reply. The issue has just been fixed.
Thanks for reporting.
