### ISSUE TITLE
GoogleTaskUsageTraceReader will not update the resource usage of cloudlets

### ISSUE THREAD

**Issue by jmsw4bn** [manoelcampos/cloudsimplus#379]
# ISSUE

## Actual behaviour

GoogleTaskUsageTraceReader will not update the resource usage of cloudlets

## Expected behaviour 

GoogleTaskUsageTraceReader should update the resource usage of cloudlets according to a google task-usage file

## Scenario 

I tested the GoogleTaskEventsExample1，and found that “0 Cloudlets processed from the workload/google-traces/task-usage-sample-1.csv trace file.”. This means that no update operation was performed on cloudlets.

According to my debuging, I found that in line 378 of the GoogleTaskUsageTraceReader.java file, getAvailableObjects() returns no values. This is because only the GoogleTaskEventsTraceReader add Available Object to availableObjectsMap. The availableObjectsMap is not shared by GoogleTaskUsageTraceReader. For GoogleTaskUsageTraceReader,  its availableObjectsMap has no item (size =0). Therefore, GoogleTaskUsageTraceReader cannot get any created cloudlet, and cannot update any cloudlet.

**Comment by jlxcsong** [comment]
您好！您发的邮件我已收到！

**Comment by manoelcampos** [comment]
Hello @jmsw4bn 
Sorry for the late reply.
I've just fixed the issue. Check commit 4b3667677 message for details.
Some design improvements had to be done, slightly changing the way to use `GoogleTaskUsageTraceReader`
`GoogleTaskEventsExample1` was updated to reflect those changes.

Thanks for reporting.
